const TRUCK_TYPES = [
  {
    id: 'sprinter',
    name: 'Sprinter / Kastenwagen',
    length: 3.70,
    width: 1.75,
    maxWeight: 1200,
    category: 'Transporter',
    note: 'Typischer Laderaum bis 3,7 m',
  },
  {
    id: 'transporter_35t',
    name: 'Transporter 3,5 t',
    length: 4.20,
    width: 2.10,
    maxWeight: 1500,
    category: 'Transporter',
    note: 'z.B. Iveco Daily, Mercedes Sprinter XL',
  },
  {
    id: 'lk_75t_plane',
    name: 'LKW 7,5 t – Plane',
    length: 6.00,
    width: 2.45,
    maxWeight: 3000,
    category: 'LKW',
    note: 'Standard-Aufbau, ca. 33 Lademeter-Äquivalent',
  },
  {
    id: 'lk_75t_koffer',
    name: 'LKW 7,5 t – Koffer',
    length: 6.00,
    width: 2.35,
    maxWeight: 2800,
    category: 'LKW',
    note: 'Geschlossener Kofferaufbau',
  },
  {
    id: 'lk_12t_plane',
    name: 'LKW 12 t – Plane',
    length: 7.20,
    width: 2.45,
    maxWeight: 6000,
    category: 'LKW',
    note: 'Mittelklasse-Verteiler',
  },
  {
    id: 'lk_12t_koffer',
    name: 'LKW 12 t – Koffer',
    length: 7.20,
    width: 2.35,
    maxWeight: 5800,
    category: 'LKW',
    note: 'Möbel-/Umzugskoffer',
  },
  {
    id: 'lk_18t',
    name: 'LKW 18 t – Plane',
    length: 7.80,
    width: 2.45,
    maxWeight: 11000,
    category: 'LKW',
    note: 'Schwere Verteilung',
  },
  {
    id: 'sattel_standard',
    name: 'Sattelzug – Standard',
    length: 13.60,
    width: 2.48,
    maxWeight: 24000,
    category: 'Sattelzug',
    note: 'EU-Länge 13,6 m Ladeboden',
  },
  {
    id: 'sattel_mega',
    name: 'Sattelzug – Mega / Jumbo',
    length: 13.60,
    width: 2.48,
    maxWeight: 24000,
    category: 'Sattelzug',
    note: 'Erhöhte Innenhöhe (3 m), gleiche Grundfläche',
  },
  {
    id: 'sattel_kurz',
    name: 'Sattelzug – Kurz (City)',
    length: 10.00,
    width: 2.48,
    maxWeight: 18000,
    category: 'Sattelzug',
    note: 'Für beengte Zufahrten',
  },
  {
    id: 'anhaenger_plane',
    name: 'Anhänger – Plane',
    length: 7.00,
    width: 2.48,
    maxWeight: 8000,
    category: 'Anhänger',
    note: 'Einzelanhänger, typisch 7 m',
  },
  {
    id: 'anhaenger_lang',
    name: 'Anhänger – Lang',
    length: 13.60,
    width: 2.48,
    maxWeight: 18000,
    category: 'Anhänger',
    note: 'Großanhänger / Sattelauflieger-Ersatz',
  },
  {
    id: 'kuehl',
    name: 'Kühl-LKW / Kühl-Sattel',
    length: 13.60,
    width: 2.45,
    maxWeight: 22000,
    category: 'Spezial',
    note: 'Isolierter Kühlaufbau',
  },
  {
    id: 'tieflader',
    name: 'Tieflader (Ladeboden)',
    length: 12.00,
    width: 2.55,
    maxWeight: 35000,
    category: 'Spezial',
    note: 'Schwerlast / Maschinentransport',
  },
  {
    id: 'custom',
    name: 'Benutzerdefiniert …',
    length: 6.00,
    width: 2.45,
    maxWeight: 3000,
    category: 'Individuell',
    note: 'Eigene Maße eingeben',
  },
];

const CARGO_PRESETS = [
  { id: 'europalette', name: 'Europalette', length: 1.20, width: 0.80, color: '#3b82f6' },
  { id: 'industriepalette', name: 'Industriepalette', length: 1.20, width: 1.00, color: '#6366f1' },
  { id: 'gitterbox', name: 'Gitterbox (GL)', length: 1.20, width: 0.80, color: '#8b5cf6' },
  { id: 'halbpalette', name: 'Halbpalette', length: 0.80, width: 0.60, color: '#06b6d4' },
  { id: 'ibc', name: 'IBC-Container', length: 1.20, width: 1.00, color: '#14b8a6' },
  { id: 'rollcontainer', name: 'Rollcontainer', length: 0.80, width: 0.70, color: '#f59e0b' },
  { id: 'kiste_klein', name: 'Kiste klein', length: 0.60, width: 0.40, color: '#f97316' },
  { id: 'kiste_gross', name: 'Kiste groß', length: 1.20, width: 0.80, color: '#ef4444' },
  { id: 'wt_runge_120', name: 'WT Runge', length: 1.20, width: 0.60, color: '#22c55e' },
  { id: 'transport_runge_330', name: 'Transport-Runge', length: 3.30, width: 0.60, color: '#0ea5e9' },
  { id: 'transport_runge_500', name: 'Transport-Runge', length: 5.00, width: 0.60, color: '#a855f7' },
];

const CARGO_COLORS = [
  '#3b82f6', '#6366f1', '#8b5cf6', '#06b6d4',
  '#14b8a6', '#22c55e', '#f59e0b', '#f97316',
  '#ef4444', '#ec4899', '#a855f7', '#0ea5e9',
];
