const logistikPrograms = [
  {
    id: "logistik-ladeplan",
    name: "Zweidimensionaler Ladeplan",
    description: "Zweidimensionaler Beladungsplaner für LKW jeglicher Art.",
    iconUrl: "programs/ladeplan/icons/ladeplan.svg",
    accent: "#3b82f6",
    type: "embed",
    url: "programs/ladeplan/index.html",
  },
  {
    id: "logistik-abc",
    name: "ABC-Analyse",
    description: "Bestands- und Umsatzklassifikation nach Jahresverbrauchswert.",
    iconUrl: "programs/abc-analyse/abc-icon.png",
    accent: "#e07a4a",
    type: "embed",
    url: "programs/abc-analyse/index.html",
  },
  {
    id: "logistik-lagerzonen",
    name: "ABC-Lagerzonen",
    description: "Einrichtungsprogramm für ABC-Lagerzonen und Kragarmregale.",
    iconUrl: "programs/abc-lagerzonen/assets/lagerzonen-icon.png",
    accent: "#3d8b4a",
    type: "embed",
    url: "programs/abc-lagerzonen/index.html",
  },
  {
    id: "logistik-europalette",
    name: "Europalettenschein",
    description: "Schein für Europaletten und Neutralen Schein erstellen, ausfüllen und drucken.",
    iconUrl: "programs/europalettenschein/europalettentausch-icon.png",
    accent: "#e8c36a",
    type: "embed",
    url: "programs/europalettenschein/index.html",
  },
  {
    id: "logistik-stochastik",
    name: "Stochastische Bedarfsanalyse",
    description: "Bestandsplanung unter Unsicherheit mit Bedarf, Streuung und Servicegrad.",
    iconUrl: "programs/stochastik/assets/stochastik-icon.png",
    accent: "#22c55e",
    type: "embed",
    url: "programs/stochastik/index.html",
  },
  {
    id: "logistik-lagerplanung",
    name: "Lagerplanung",
    description: "Maßstabsgetreuer Grundriss für Blocklager, Paletten- und Kragarmregale.",
    iconUrl: "programs/lagerplanung/icons/lagerplanung-icon.png",
    accent: "#a855f7",
    type: "embed",
    url: "programs/lagerplanung/index.html",
  },
];
